name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: src/package.json
        cache-dependency-path: src/package-lock.json

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: jamesread
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_TOKEN }}

    - name: Make npm install
      run: make -wC frontend

    - name: Make dist-prod
      run: make -w dist-prod

    - name: Get date
      run: |
        echo "DATE=$(date +'%s')" >> "$GITHUB_ENV"

    - name: Build the Container image
      run: docker build . --file Dockerfile --tag ghcr.io/jamesread/spoon-check:${{ env.DATE }}

    - name: Tag latest
      run: docker tag ghcr.io/jamesread/spoon-check:${{ env.DATE }} ghcr.io/jamesread/spoon-check:latest

    - name: Push the Container image
      run: docker push ghcr.io/jamesread/spoon-check:${{ env.DATE }}

    - name: Push the Container image - latest tag
      run: docker push ghcr.io/jamesread/spoon-check:latest
